type: cloze
uuid: d3941310-501c-11e3-8f96-0800200c9a66
name: 'Cloze question'
description: 'Quiz questions that allow a user to fill-in the missing words.'
create_body_label: 'Question'
help: ''
has_title: true
title_label: Title
settings:
  node:
    preview: 1
    options:
      status: status
      # Promoted to front page.
      promote: false
      sticky: '0'
      revision: '0'
    submitted: true
status: true
langcode: en
